services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secretPassword
      MONGO_INITDB_DATABASE: order_management
    volumes:
      - mongo_data:/data/db
    networks:
      - spring-mongo-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  spring-boot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot_container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:secretPassword@mongodb:27017/order_management?authSource=admin
      MONGODB_DATABASE: order_management
    depends_on:
      mongodb:
          condition: service_healthy
    networks:
      - spring-mongo-network
    restart: unless-stopped

volumes:
  mongo_data:

networks:
  spring-mongo-network:
    driver: bridge
